version: '3'
services:
  www:
    volumes:
      - /home/kalina/projects/wbo/server-data:/home/kalina/projects/wbo/server-data
    ports:
      - '80:80'
      - '5005:5005'
    build:
      context: .
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s

